<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<met#aeb3b8et="utf-8">';
echo '<title>Niranjan-Portfolio</title>';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '<meta content="Free Website Template" name="keywords">';
echo '<meta content="Free Website Template" name="description">';
echo '';
echo '<!-- Favicon -->';
echo '<link href="img/favicon.ico" rel="icon">';
echo '';
echo '<!-- Google Web Fonts -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@300;400;500;600;700&display=swap" rel="stylesheet">';
echo '';
echo '<!-- Icon Font Stylesheet -->';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">';
echo '';
echo '<!-- Libraries Stylesheet -->';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">';
echo '<link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">';
echo '<link href="lib/animate/animate.min.css" rel="stylesheet">';
echo '';
echo '<!-- Customized Bootstrap Stylesheet -->';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '<!-- Template Stylesheet -->';
echo '<link href="css/style.css" rel="stylesheet">';
echo '</head>';
echo '';
echo '<body>';
echo '<!-- Spinner Start -->';
echo '<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">';
echo '<div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">';
echo '<span class="sr-only">Loading...</span>';
echo '</div>';
echo '</div>';
echo '<!-- Spinner End -->';
echo '';
echo '<div class="container">';
echo '<div class="row g-5">';
echo '<div class="col-lg-4 sticky-lg-top vh-100">';
echo '<div class="d-flex flex-column h-100 text-center overflow-auto shadow">';
echo '<img class="w-100 img-fluid mb-4" src="img/profile.jpg" alt="Image">';
echo '<h1 class="text-primary mt-2">Niranjan sah</h1>';
echo '<div class="mb-4" style="height: 22px;">';
echo '<h4 class="typed-text-output d-inline-block text-light"></h4>';
echo '<div class="typed-text d-none">Web Designer, Web Developer,Programmer, App Designer, App Developer</div>';
echo '</div>';
echo '<div class="d-flex justify-content-center mt-auto mb-3">';
echo '<a class="btn btn-secondary btn-square mx-1" href="https://twitter.com/Niranja36990458?t=kxGD6kMQ7rtb3E2f2v7G7A&s=08"><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-secondary btn-square mx-1" href="https://www.facebook.com/niranjan8790"><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-secondary btn-square mx-1" href="www.linkedin.com/in/niranjan-sah"><i class="fab fa-linkedin-in"></i></a>';
echo '<a class="btn btn-secondary btn-square mx-1" href="https://www.instagram.com/niranjansah_786/"><i class="fab fa-instagram"></i></a>';
echo '<a class="btn btn-secondary btn-square mx-1" href="https://github.com/niranjan8790"><i class="fab fa-github"></i></a>';
echo '</div>';
echo '<div class="d-flex align-items-end justify-content-between border-top">';
echo '<a href="D:\Niranjan\NiranjanCV.pdf" class="btn w-50 border-end">Download CV</a>';
echo '<a href="https://mail.google.com/mail" class="btn w-50 btn-scroll">Contact Me</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-8">';
echo '<!-- About Start -->';
echo '<section class="py-5 border-bottom wow fadeInUp" data-wow-delay="0.1s">';
echo '<h1 class="title pb-3 mb-5">About Me</h1>';
echo '<p>I was born on July 11th 2003 in Nepal and currently persuding Computer Science & Information Technology at the KL University-Vijayawada-Andhra Pradesh-India.<br><br>I started web design and development recently and enjoying working as web designer.I am currently available for freelance work.I am passionate about improving the lives of others through design and i am constantly looking to learn new things everyday.</p>';
echo '<div class="row mb-4">';
echo '<div class="col-sm-6 py-1">';
echo '<span class="fw-medium text-primary">Name:</span> Niranjan sah';
echo '</div>';
echo '<div class="col-sm-6 py-1">';
echo '<span class="fw-medium text-primary">Birthday:</span> 11 july 2003';
echo '</div>';
echo '<div class="col-sm-6 py-1">';
echo '<span class="fw-medium text-primary">Degree:</span> B tech';
echo '</div>';
echo '<div class="col-sm-6 py-1">';
echo '<span class="fw-medium text-primary">Experience:</span> 2 Years';
echo '</div>';
echo '<div class="col-sm-6 py-1">';
echo '<span class="fw-medium text-primary">Phone:</span> +91 8002004609(IN) <br>+977 9826753490(NP)';
echo '</div>';
echo '<div class="col-sm-6 py-1">';
echo '<span class="fw-medium text-primary">Email:</span> sahn0075@gmail.com';
echo '</div>';
echo '<div class="col-sm-6 py-1">';
echo '<span class="fw-medium text-primary">Address:</span> Siraha,nepal';
echo '</div>';
echo '<div class="col-sm-6 py-1">';
echo '<span class="fw-medium text-primary">Freelance:</span> Available';
echo '</div>';
echo '</div>';
echo '<div class="row g-4">';
echo '<div class="col-md-4 col-lg-6 col-xl-4">';
echo '<div class="d-flex bg-secondary p-4">';
echo '<h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">2</h1>';
echo '<div class="ps-3">';
echo '<p class="mb-0">Years of</p>';
echo '<h5 class="mb-0">Experience</h5>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 col-lg-6 col-xl-4">';
echo '<div class="d-flex bg-secondary p-4">';
echo '<h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">50</h1>';
echo '<div class="ps-3">';
echo '<p class="mb-0">Happy</p>';
echo '<h5 class="mb-0">Clients</h5>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 col-lg-6 col-xl-4">';
echo '<div class="d-flex bg-secondary p-4">';
echo '<h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">50</h1>';
echo '<div class="ps-3">';
echo '<p class="mb-0">Complete</p>';
echo '<h5 class="mb-0">Projects</h5>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- About End -->';
echo '';
echo '<!-- Skills Start -->';
echo '<section class="py-5 border-bottom wow fadeInUp" data-wow-delay="0.1s">';
echo '<h1 class="title pb-3 mb-5">Skills</h1>';
echo '<div class="row">';
echo '<div class="col-sm-6">';
echo '<div class="skill mb-4">';
echo '<div class="d-flex justify-content-between">';
echo '<p class="mb-2">HTML</p>';
echo '<p class="mb-2">95%</p>';
echo '</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-primary" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>';
echo '</div>';
echo '</div>';
echo '<div class="skill mb-4">';
echo '<div class="d-flex justify-content-between">';
echo '<p class="mb-2">CSS</p>';
echo '<p class="mb-2">85%</p>';
echo '</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-warning" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>';
echo '</div>';
echo '</div>';
echo '<div class="skill mb-4">';
echo '<div class="d-flex justify-content-between">';
echo '<p class="mb-2">PHP</p>';
echo '<p class="mb-2">75%</p>';
echo '</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-danger" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-6">';
echo '<div class="skill mb-4">';
echo '<div class="d-flex justify-content-between">';
echo '<p class="mb-2">Javascript</p>';
echo '<p class="mb-2">80%</p>';
echo '</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-danger" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>';
echo '</div>';
echo '</div>';
echo '<div class="skill mb-4">';
echo '<div class="d-flex justify-content-between">';
echo '<p class="mb-2">Angular JS</p>';
echo '<p class="mb-2">70%</p>';
echo '</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-success" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>';
echo '</div>';
echo '</div>';
echo '<div class="skill mb-4">';
echo '<div class="d-flex justify-content-between">';
echo '<p class="mb-2">Wordpress</p>';
echo '<p class="mb-2">90%</p>';
echo '</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-info" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Skills End -->';
echo '';
echo '<!-- Expericence Start -->';
echo '<section class="py-5 wow fadeInUp" data-wow-delay="0.1s">';
echo '<h1 class="title pb-3 mb-5">Expericence</h1>';
echo '<div class="border-start border-2 border-light pt-2 ps-5">';
echo '<div class="position-relative mb-4">';
echo '<span class="bi bi-arrow-right fs-4 text-light position-absolute" style="top: -5px; left: -50px;"></span>';
echo '<h5 class="mb-1">Web Designer</h5>';
echo '<p class="mb-2">Freelancer | <small>2021 - Present</small></p>';
echo '<p>I am working as web designer.I used to design web pages and build websites.</p>';
echo '</div>';
echo '<div class="position-relative mb-4">';
echo '<span class="bi bi-arrow-right fs-4 text-light position-absolute" style="top: -5px; left: -50px;"></span>';
echo '<h5 class="mb-1">App Developer</h5>';
echo '<p class="mb-2">Freelancer | <small>2021- Present</small></p>';
echo '<p>My role as a app developer is to Collaborate with development team and other IT staff to set specifications for new applications And Writing high-quality code.</p>';
echo '</div>';
echo '<div class="position-relative mb-4">';
echo '<span class="bi bi-arrow-right fs-4 text-light position-absolute" style="top: -5px; left: -50px;"></span>';
echo '<h5 class="mb-1">Data Analyst</h5>';
echo '<p class="mb-2">FreeLancer| <small>2021- 2050</small></p>';
echo '<p>I am also working as data analyst .My responsibility as a data analyst is to';
echo '<br> •	Developing and maintaining databases, data systems.';
echo '<br>•	Removing corrupted data and fixing coding errors and related problems';
echo '<br>•	Fixing coding errors and related problems';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Expericence End -->';
echo '';
echo '<!-- Subscribe Start -->';
echo '<section class="wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="bg-secondary text-center p-5">';
echo '<h1 class="text-white font-weight-bold">Subscribe My Newsletter</h1>';
echo '<p class="text-white">Subscribe and get my latest article in your inbox</p>';
echo '<div class="position-relative w-100">';
echo '<input class="form-control bg-dark border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">';
echo '<button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">Subscribe</button>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Subscribe End -->';
echo '';
echo '<!-- Services Start -->';
echo '<section class="py-5 border-bottom wow fadeInUp" data-wow-delay="0.1s">';
echo '<h1 class="title pb-3 mb-5">Services</h1>';
echo '<div class="row g-4">';
echo '<div class="col-md-6">';
echo '<div class="service-item">';
echo '<i class="fa fa-2x fa-laptop-code mx-auto mb-4"></i>';
echo '<h5 class="mb-2">Web Design</h5>';
echo '<p class="mb-0">Web designers are the individuals who are involved in designing and building the interface.They work in IT team of an organization and also for a digital media agency.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6">';
echo '<div class="service-item">';
echo '<i class="fab fa-2x fa-android mx-auto mb-4"></i>';
echo '<h5 class="mb-2">App Development</h5>';
echo '<p class="mb-0">App developer roles include analyzing data to determine an application's specifications and requirements; sometimes developers collaborate with other computer specialists during this process. </p>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6">';
echo '<div class="service-item">';
echo '<i class="fa fa-2x fa-search mx-auto mb-4"></i>';
echo '<h5 class="mb-2">DATA ANALYSIS</h5>';
echo '<p class="mb-0">The purpose of Data Analysis is to extract useful information from data and taking the decision based upon the data analysis.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6">';
echo '<div class="service-item">';
echo '<i class="fa fa-2x fa-edit mx-auto mb-4"></i>';
echo '<h5 class="mb-2">Content Creating</h5>';
echo '<p class="mb-0">Content creation is the contribution of information to any media and most especially to digital media for an end-user/audience in specific contexts.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Services End -->';
echo '';
echo '<!-- Portfolio Start -->';
echo '<section class="py-5 border-bottom wow fadeInUp" data-wow-delay="0.1s">';
echo '<h1 class="title pb-3 mb-5">Portfolio</h1>';
echo '<div class="row">';
echo '<div class="col-12">';
echo '<div class="row">';
echo '<div class="col-12 text-center mb-2">';
echo '<ul class="list-inline mb-4" id="portfolio-flters">';
echo '<li class="btn btn-secondary active"  data-filter="*"><i class="fa fa-star me-2"></i>All</li>';
echo '<li class="btn btn-secondary" data-filter=".first"><i class="fa fa-laptop-code me-2"></i>Design</li>';
echo '<li class="btn btn-secondary" data-filter=".second"><i class="fa fa-mobile-alt me-2"></i>Development</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="row portfolio-container">';
echo '<div class="col-md-6 mb-4 portfolio-item first">';
echo '<div class="position-relative overflow-hidden mb-2">';
echo '<img class="img-fluid w-100" src="img/portfolio-1.jpg" alt="">';
echo '<div class="portfolio-btn d-flex align-items-center justify-content-center">';
echo '<a href="img/portfolio-1.jpg" data-lightbox="portfolio">';
echo '<i class="bi bi-plus text-light"></i>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 mb-4 portfolio-item second">';
echo '<div class="position-relative overflow-hidden mb-2">';
echo '<img class="img-fluid w-100" src="img/portfolio-2.jpg" alt="">';
echo '<div class="portfolio-btn d-flex align-items-center justify-content-center">';
echo '<a href="img/portfolio-2.jpg" data-lightbox="portfolio">';
echo '<i class="bi bi-plus text-light"></i>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 mb-4 portfolio-item first">';
echo '<div class="position-relative overflow-hidden mb-2">';
echo '<img class="img-fluid w-100" src="img/portfolio-3.jpg" alt="">';
echo '<div class="portfolio-btn d-flex align-items-center justify-content-center">';
echo '<a href="img/portfolio-3.jpg" data-lightbox="portfolio">';
echo '<i class="bi bi-plus text-light"></i>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 mb-4 portfolio-item second">';
echo '<div class="position-relative overflow-hidden mb-2">';
echo '<img class="img-fluid w-100" src="img/portfolio-4.jpg" alt="">';
echo '<div class="portfolio-btn d-flex align-items-center justify-content-center">';
echo '<a href="img/portfolio-4.jpg" data-lightbox="portfolio">';
echo '<i class="bi bi-plus text-light"></i>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Portfolio End -->';
echo '';
echo '<!-- Testimonial Start -->';
echo '<section class="py-5 border-bottom wow fadeInUp" data-wow-delay="0.1s">';
echo '<h1 class="title pb-3 mb-5">Testimonial</h1>';
echo '<div class="owl-carousel testimonial-carousel">';
echo '<div class="text-left">';
echo '<i class="fa fa-3x fa-quote-left text-primary mb-4"></i>';
echo '<p class="fs-4 mb-4">"Any fool can write code that a computer can understand. Good programmers write code that humans can understand.”</p>';
echo '<div class="d-flex align-items-center">';
echo '<img class="img-fluid" src="img/testimonial-1.jfif" style="width: 60px; height: 60px;">';
echo '<div class="ps-3">';
echo '<p class="text-primary fs-5 mb-1">Martin Fowler</p>';
echo '<i>British software developer</i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="text-left">';
echo '<i class="fa fa-3x fa-quote-left text-primary mb-4"></i>';
echo '<p class="fs-4 mb-4">“Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.”</p>';
echo '<div class="d-flex align-items-center">';
echo '<img class="img-fluid" src="img/testimonial-2.jfif" style="width: 60px; height: 60px;">';
echo '<div class="ps-3">';
echo '<p class="text-primary fs-5 mb-1">Dan Salomon</p>';
echo '<i>Republican Member</i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="text-left">';
echo '<i class="fa fa-3x fa-quote-left text-primary mb-4"></i>';
echo '<p class="fs-4 mb-4">“ Code is like humor. When you have to explain it, it’s bad.”</p>';
echo '<div class="d-flex align-items-center">';
echo '<img class="img-fluid" src="img/testimonial-3.jfif" style="width: 60px; height: 60px;">';
echo '<div class="ps-3">';
echo '<p class="text-primary fs-5 mb-1">Cory House</p>';
echo '<i>Founder of Bitnative LLC</i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Testimonial End -->';
echo '';
echo '<!-- Contact Start -->';
echo '<section class="py-5 wow fadeInUp" data-wow-delay="0.1s" id="contact">';
echo '<h1 class="title pb-3 mb-5">Contact Me</h1>';
echo '<p class="mb-4">If any queries,Send me the mail <a href="https://htmlcodex.com/contact-form">Download Now</a></p>';
echo '<form>';
echo '<div class="row g-3">';
echo '<div class="col-md-6">';
echo '<div class="form-floating">';
echo '<input type="text" class="form-control border-0 bg-secondary" id="name" placeholder="Your Name">';
echo '<label for="name">Your Name</label>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6">';
echo '<div class="form-floating">';
echo '<input type="email" class="form-control border-0 bg-secondary" id="email" placeholder="Your Email">';
echo '<label for="email">Your Email</label>';
echo '</div>';
echo '</div>';
echo '<div class="col-12">';
echo '<div class="form-floating">';
echo '<input type="text" class="form-control border-0 bg-secondary" id="subject" placeholder="Subject">';
echo '<label for="subject">Subject</label>';
echo '</div>';
echo '</div>';
echo '<div class="col-12">';
echo '<div class="form-floating">';
echo '<textarea class="form-control border-0 bg-secondary" placeholder="Leave a message here" id="message" style="height: 200px"></textarea>';
echo '<label for="message">Give your feedback</label>';
echo '</div>';
echo '</div>';
echo '<div class="col-12">';
echo '<button class="btn btn-primary w-100 py-3" type="submit">Send mail</button>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</section>';
echo '<!-- Contact End -->';
echo '';
echo '<!-- Footer Start -->';
echo '<section class="wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="bg-secondary text-light text-center p-5">';
echo '<div class="d-flex justify-content-center mb-4">';
echo '<a class="btn btn-secondary btn-square mx-1" href="https://twitter.com/Niranja36990458?t=kxGD6kMQ7rtb3E2f2v7G7A&s=08"><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-secondary btn-square mx-1" href="https://www.facebook.com/niranjan8790"><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-secondary btn-square mx-1" href="www.linkedin.com/in/niranjan-sah"><i class="fab fa-linkedin-in"></i></a>';
echo '<a class="btn btn-secondary btn-square mx-1" href="https://www.instagram.com/niranjansah_786/"><i class="fab fa-instagram"></i></a>';
echo '<a class="btn btn-secondary btn-square mx-1" href="https://github.com/niranjan8790"><i class="fab fa-github"></i></a>';
echo '</div>';
echo '<div class="d-flex justify-content-center mb-3">';
echo '<a class="text-light px-3 border-end" href="#">Privacy</a>';
echo '<a class="text-light px-3 border-end" href="#">Terms</a>';
echo '<a class="text-light px-3 border-end" href="#">FAQs</a>';
echo '<a class="text-light px-3" href="#">Help</a>';
echo '</div>';
echo '';
echo '<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->';
echo '<p class="m-0">&copy; Designed by <a href="http://niranjansah.com.np/">Code with niranjan</a></p>';
echo '</div>';
echo '</section>';
echo '<!-- Footer End -->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<!-- Back to Top -->';
echo '<a href="#" class="back-to-top"><i class="fa fa-angle-double-up"></i></a>';
echo '';
echo '<!-- JavaScript Libraries -->';
echo '<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>';
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/wow/wow.min.js"></script>';
echo '<script src="lib/typed/typed.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/waypoints/waypoints.min.js"></script>';
echo '<script src="lib/counterup/counterup.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '<script src="lib/isotope/isotope.pkgd.min.js"></script>';
echo '<script src="lib/lightbox/js/lightbox.min.js"></script>';
echo '';
echo '<!-- Contact Javascript File -->';
echo '<script src="mail/jqBootstrapValidation.min.js"></script>';
echo '<script src="mail/contact.js"></script>';
echo '';
echo '<!-- Template Javascript -->';
echo '<script src="js/main.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>